### ISSUE TITLE
Improved examples?

### ISSUE THREAD

**Issue by oxinabox** [adolgert/UnitTestDesign.jl#32]
Right now there is an example in the docs.
But it a runable example that shows both the code under test and how it is tested.
And highlights how the combinatorial approach catched (or if misapplied failed to catch) all branches.

**Comment by adolgert** [comment]
A more complete example would help. While I've used this technique a lot, my real-world examples are too large to use. I need to think, because your suggestion is helpful.

And I fear that the docs gave the impression that combinatorial testing finds all branches, an impression they gave by saying, "combinatorial testing finds all branches," and that's totally not true. It's just a good bet at finding branches.
